lane :test do
      google_chat(
            webhook: '',
            headerTitle: '',
            headerSubTitle: '',
            headerImageUrl: '',
            bodyTitle1: '',
            bodySubtitle1: '',
            bodyTitle2: '',
            bodySubtitle2: '',
            bodyTitle3: '',
            bodySubtitle3: '',
            bodyTitle4: '',
            bodySubtitle4: '',
            mentions: ''
      )
end
